server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
spring:
  application:
    name: cloud-order-service