server:
  port: 7001
eureka:
  instance:
    hostname: eureka1.com
  client:
    #表示不向注册中心注册自己
    register-with-eureka: false
    #false 表示自己就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/

